<?php

/**
 * This file is part of TodoList\tasks package.
 */

namespace App\Tasks\Gateway;

use App\Common\Gateway\Gateway;

/**
 * TaskGateway.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskGateway extends Gateway
{
}
