<?php

namespace App\Users\Gateway;

use App\Common\Gateway\Gateway;

/**
 * UserGateway.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGateway extends Gateway
{
}
