filter:
    excluded_paths:
        - vendor/*
        - tests/*
        - spec/*

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3

build:
    environment:
        php: 5.6
    tests:
        override:
            -
                command: './bin/phpspec run'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'

    dependencies:
        before:
            - cp app/config/parameters.php.dist app/config/parameters.php
            - cp composer.lock.scrutinizer.dist composer.lock
            - mkdir -p ./var/logs
            - chmod -R 777 ./var/logs
            - mkdir -p ./var/cache
            - chmod -R 777 ./var/cache
            - mkdir -p ./var/jws
            - openssl genrsa -aes256  -passout pass:foobar -out ./var/jws/private.pem 4096
            - openssl rsa -passin pass:foobar -pubout -in ./var/jws/private.pem -out ./var/jws/public.pem
            - cp app/config/parameters.php.dist app/config/parameters.php
            - composer install --prefer-source --no-interaction --dev --optimize-autoloader
            - cp phpspec.yml.dist phpspec.yml
