filter:
    excluded_paths:
        - vendor/*
        - tests/*
        - spec/*
build:
    environment:
        php: 5.6
    tests:
        override:
            -
                command: './bin/phpspec run'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'

    dependencies:
        before:
            - cp app/config/parameters.php.dist app/config/parameters.php
            - cp phpspec.yml.dist phpspec.yml

checks:
    php:
        code_rating: true
        duplication: true
