filter:
    excluded_paths:
        - vendor/*
        - tests/*
        - spec/*

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3

build:
    environment:
        php: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'

    dependencies:
        before:
            - cp app/config/parameters.php.dist app/config/parameters.php
            - cp composer.lock.dist.scrutinizer composer.lock
